### ISSUE TITLE
A few fix about the Makefile

### ISSUE THREAD

**Issue by songzeceng** [brandenburg/feather-trace#1]
The location of xxx.o should be ahead of XXX, or there will be an error during build which said undefined reference to (dlsym、alloc_flushed_ft_buffer and so on) even if the head file is included, can be found and the make flag -ldl is added which are already done in your Makefile
After my practice, lines modified come together at the bottom of Makefile and here they are
```
all: ${TARGETS}

static_example: ${FT_STATIC}  static_example.o

buffer_example:  ${FT_STATIC}  buffer_example.o

mutex_example: mutex_example.o
        # modified
	${CC} mutex_example.o ${LDFLAGS} -lpthread -o mutex_example

heapstat_example: heapstat_example.o
	${CC} ${LDFLAGS} -o $@ $^

libso.so: example_lib.o
	${CC} ${LDFLAGS} -shared -T feather-trace.ld.S -o libso.so example_lib.o

dynamic_example:  ${FT_DYNAMIC}  dynamic_example.o libso.so
        # modified
	${CC} dynamic_example.o ${LDFLAGS} -L. -o dynamic_example -lso -ldl  ${FT_DYNAMIC}

libpthread_preload.so: pthread_preload.o ${FT_STATIC} libft_saved.so
        # modified
	${CC} pthread_preload.o ${LDFLAGS} -L. -lft_saved -shared -T feather-trace.ld.S -o libpthread_preload.so ${FT_STATIC}

libheapstat_preload.so: heapstat_preload.o ${FT_STATIC} libft_saved.so
	${CC} ${LDFLAGS} -L. -lpthread -lft_saved -shared -T feather-trace.ld.S -o $@ $< ${FT_STATIC}

libft_saved.so: ft_save_d.o
        # modified
	${CC} ft_save_d.o ${LDFLAGS} -lpthread -shared -T feather-trace.ld.S  -o libft_saved.so

mutex_ft2csv: mutex_ft2csv.o

heapstat_ft2csv: heapstat_ft2csv.o

clean:
	rm -rf *.o *.so ${TARGETS}
```

**Comment by brandenburg** [comment]
Thanks for noticing. Can you please submit a pull request?

**Comment by songzeceng** [comment]
> Thanks for noticing. Can you please submit a pull request?
> […](#)
> On 23. Oct 2020, at 02:55, songzeceng ***@***.***> wrote: ﻿ The location of xxx.o should be ahead of XXX, or there will be an error during build which said undefined reference to (dlsym、alloc_flushed_ft_buffer and so on) even if the head file is included, can be found and the make flag -ldl is added which are already done in your Makefile After my practice, lines modified come together at the bottom of Makefile and here they are all: ${TARGETS} static_example: ${FT_STATIC} static_example.o buffer_example: ${FT_STATIC} buffer_example.o mutex_example: mutex_example.o # modified ${CC} mutex_example.o ${LDFLAGS} -lpthread -o mutex_example heapstat_example: heapstat_example.o ${CC} ${LDFLAGS} -o $@ $^ libso.so: example_lib.o ${CC} ${LDFLAGS} -shared -T feather-trace.ld.S -o libso.so example_lib.o dynamic_example: ${FT_DYNAMIC} dynamic_example.o libso.so # modified ${CC} dynamic_example.o ${LDFLAGS} -L. -o dynamic_example -lso -ldl ${FT_DYNAMIC} libpthread_preload.so: pthread_preload.o ${FT_STATIC} libft_saved.so # modified ${CC} pthread_preload.o ${LDFLAGS} -L. -lft_saved -shared -T feather-trace.ld.S -o libpthread_preload.so ${FT_STATIC} libheapstat_preload.so: heapstat_preload.o ${FT_STATIC} libft_saved.so ${CC} ${LDFLAGS} -L. -lpthread -lft_saved -shared -T feather-trace.ld.S -o $@ $< ${FT_STATIC} libft_saved.so: ft_save_d.o # modified ${CC} ft_save_d.o ${LDFLAGS} -lpthread -shared -T feather-trace.ld.S -o libft_saved.so mutex_ft2csv: mutex_ft2csv.o heapstat_ft2csv: heapstat_ft2csv.o clean: rm -rf *.o *.so ${TARGETS} — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.

Pull request has been submitted and please check it out.

**Comment by brandenburg** [comment]
I have not been able to reproduce the problem. With which compiler / linker do you see the failure?

**Comment by songzeceng** [comment]
> I have not been able to reproduce the problem. With which compiler / linker do you see the failure?

gcc/g++7.5

**Comment by brandenburg** [comment]
Thank you for reporting this. I've merged your patch.

**Comment by songzeceng** [comment]
> Thank you for reporting this. I've merged your patch.

My pleasure
